### ISSUE TITLE
大佬，数据不更新了么？求一个闪存的flash id 参数。我自己找不到

### ISSUE THREAD

**Issue by dylanleesky** [PeratX/FlashMaster#1]
H27UCG8T2ETR
![小Q截图-20210526212122](https://user-images.githubusercontent.com/14555503/119666901-5eb92400-be68-11eb-862b-6cc41017bf4d.png)

**Comment by PeratX** [comment]
https://flashm.cf/#/decode?pn=H27UCG8T2ETR
