### ISSUE TITLE
Why do all antivirus software remove this file?

### ISSUE THREAD

**Issue by Muhammadyusuf96** [PeratX/FlashMaster#2]
Category: Trojan
https://www.virustotal.com/gui/file/75fde1876b18613a30a1dc14342b1196238affa336dfa62c15857c90943b8a6e/detection

**Comment by PeratX** [comment]
Mis report.
The software is written in E lang which has been used to create many malwares which results in many anti virus software will report any software written in E lang as a malware.

**Comment by PeratX** [comment]
Also, there's an alternative which is backed by the same backend.
https://flashm.cf

**Comment by andrei-cb** [comment]
> Also, there's an alternative which is backed by the same backend. https://flashm.cf

Is there another alternative? flashm.cf is no longer working
